### ISSUE TITLE
Unauthorized: The credentials were provided incorrectly or did not match any existing, active credentials. code: 401

### ISSUE THREAD

**Issue by aniruddh-deserve** [smartystreets/smartystreets-java-sdk#38] opened 2022-10-20 08:30 UTC
Unauthorized: The credentials were provided incorrectly or did not match any existing, active credentials. code: 401
 - We see this error intermittently. After checking , we found credentials are correct( loaded results for other time afterwards) and subscription is active.

**Comment by RyanLCox1** [comment] 2022-11-07 20:48
Do you have any more detail on this? Which api were you using us-street, internation_street, ? How would we reproduce this?

**Comment by aniruddh-deserve** [comment] 2022-12-12 03:13
I addition to this we also received " A GET request lacked a street field or the request body of a POST request contained malformed JSON. Bad Request (Malformed Payload)" once even when request data was sent to server.

**Comment by RyanLCox1** [comment] 2023-01-26 21:42
I'm closing that as cannot reproduce for now. Let's keep an eye on it and if you continue to have problems we can reopen this bug. Please include all possible information for us to reproduce the bug.

**Closed by RyanLCox1** 2023-01-26 21:42 UTC
